name: dashboard
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

#................... Packages .....................#

dependencies:
  flutter:
    sdk: flutter

  #Utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.1.14
  flutter_native_splash: ^2.3.3

  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  #state management
  get: ^4.6.6
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  provider: ^6.0.5


  #Product Specific
  fl_chart: ^0.64.0
  flutter_svg: ^2.0.7
  #Fonts
  google_fonts: ^6.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  #................... End Packages .....................#




  #................... Local Assets .....................#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/category/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/profile.jpg

  #................... Local Fonts .....................#

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
